#!/usr/bin/env python3
"""
Automated Setup Script for Skin Health Detection System
Generates SECRET_KEY, installs dependencies, and configures the app
"""

import os
import sys
import subprocess
import secrets
import platform
from pathlib import Path

# Force UTF-8 encoding for standard output to support emojis on Windows
if sys.stdout and hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

def print_header(text):
    print("\n" + "="*70)
    print(f"  {text}")
    print("="*70)

def print_success(text):
    print(f"✅ {text}")

def print_error(text):
    print(f"❌ {text}")

def print_info(text):
    print(f"ℹ️  {text}")

def generate_secret_key():
    """Generate a secure random SECRET_KEY"""
    return secrets.token_urlsafe(32)

def get_project_root():
    """Get the project root directory"""
    return Path(__file__).parent.resolve()

def create_env_file(project_root, secret_key):
    """Create .env file with configuration"""
    env_path = project_root / ".env"
    
    # Check if .env already exists
    if env_path.exists():
        response = input("\n.env file already exists. Overwrite? (y/n): ").lower()
        if response != 'y':
            print_info("Skipping .env creation")
            return str(env_path)
    
    env_content = f"""# Skin Health Detection System Configuration
# Generated by setup.py

# SECURITY: Secret key for JWT token generation
# Keep this secure and never commit it to version control
SECRET_KEY={secret_key}

# Database configuration (optional, uses default if not set)
# DATABASE_URL=./backend/users.db

# Application settings
ENVIRONMENT=development
DEBUG=True
"""
    
    try:
        env_path.write_text(env_content)
        print_success(f"Created .env file at {env_path}")
        return str(env_path)
    except Exception as e:
        print_error(f"Failed to create .env file: {e}")
        return None

def set_environment_variable(key, value):
    """Set environment variable for current session"""
    os.environ[key] = value
    print_success(f"Set environment variable {key}")

def install_backend_dependencies(project_root):
    """Install Python backend dependencies"""
    print_header("Installing Backend Dependencies")
    
    backend_dir = project_root / "backend"
    requirements_file = backend_dir / "requirements.txt"
    
    if not requirements_file.exists():
        print_error(f"requirements.txt not found at {requirements_file}")
        return False
    
    try:
        print_info(f"Installing from {requirements_file}")
        subprocess.check_call([
            sys.executable, "-m", "pip", "install", "-r", str(requirements_file)
        ])
        print_success("Backend dependencies installed successfully")
        return True
    except subprocess.CalledProcessError as e:
        print_error(f"Failed to install backend dependencies: {e}")
        return False

def install_frontend_dependencies(project_root):
    """Install frontend dependencies with npm"""
    print_header("Installing Frontend Dependencies")
    
    frontend_dir = project_root / "frontend"
    package_json = frontend_dir / "package.json"
    
    if not package_json.exists():
        print_error(f"package.json not found at {package_json}")
        return False
    
    # Check if npm is installed
    try:
        subprocess.check_call(["npm", "--version"], 
                            stdout=subprocess.DEVNULL, 
                            stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print_error("npm is not installed. Please install Node.js and npm first.")
        print_info("Download from: https://nodejs.org/")
        return False
    
    try:
        print_info(f"Running npm install in {frontend_dir}")
        subprocess.check_call(["npm", "install"], cwd=str(frontend_dir))
        print_success("Frontend dependencies installed successfully")
        return True
    except subprocess.CalledProcessError as e:
        print_error(f"Failed to install frontend dependencies: {e}")
        return False

def create_startup_scripts(project_root, secret_key):
    """Create convenient startup scripts for different platforms"""
    print_header("Creating Startup Scripts")
    
    # Windows batch script
    if platform.system() == "Windows":
        batch_content = f'''@echo off
REM Skin Health Detection System - Startup Script for Windows
REM This script sets up the environment and starts the application

setlocal enabledelayedexpansion

REM Set environment variables
set SECRET_KEY={secret_key}

REM Add current directory to Python path
set PYTHONPATH=%cd%;!PYTHONPATH!

echo ========================================
echo Starting Backend Server...
echo ========================================
cd backend
start "Backend Server" cmd /k uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

timeout /t 3

echo.
echo ========================================
echo Starting Frontend Dev Server...
echo ========================================
cd ..\\frontend
start "Frontend Dev Server" cmd /k npm run dev

echo.
echo ========================================
echo Startup Complete!
echo ========================================
echo Backend: http://localhost:8000
echo Frontend: http://localhost:5173
echo.
pause
'''
        batch_file = project_root / "start.bat"
        try:
            batch_file.write_text(batch_content)
            print_success(f"Created startup script: {batch_file}")
            
            # Make it executable on Windows
            os.chmod(batch_file, 0o755)
        except Exception as e:
            print_error(f"Failed to create startup script: {e}")
    
    # Bash script for Linux/Mac
    bash_content = f'''#!/bin/bash
# Skin Health Detection System - Startup Script for Linux/Mac

# Set environment variables
export SECRET_KEY={secret_key}

echo "========================================"
echo "Starting Backend Server..."
echo "========================================"
cd "$(dirname "$0")/backend"
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!

sleep 2

echo ""
echo "========================================"
echo "Starting Frontend Dev Server..."
echo "========================================"
cd ../frontend
npm run dev &
FRONTEND_PID=$!

echo ""
echo "========================================"
echo "Startup Complete!"
echo "========================================"
echo "Backend: http://localhost:8000"
echo "Frontend: http://localhost:5173"
echo ""
echo "Press Ctrl+C to stop servers"
echo ""

# Wait for processes
wait $BACKEND_PID $FRONTEND_PID
'''
    
    bash_file = project_root / "start.sh"
    try:
        bash_file.write_text(bash_content)
        os.chmod(bash_file, 0o755)
        print_success(f"Created startup script: {bash_file}")
    except Exception as e:
        print_error(f"Failed to create startup script: {e}")

def verify_installation(project_root):
    """Verify that all components are installed correctly"""
    print_header("Verifying Installation")
    
    checks = {
        "Backend requirements.txt": project_root / "backend" / "requirements.txt",
        "Frontend package.json": project_root / "frontend" / "package.json",
        "Backend app.py": project_root / "backend" / "app.py",
        "Frontend src": project_root / "frontend" / "src",
        ".env file": project_root / ".env"
    }
    
    all_good = True
    for check_name, path in checks.items():
        if path.exists():
            print_success(f"{check_name} found")
        else:
            print_error(f"{check_name} NOT found")
            all_good = False
    
    return all_good

def main():
    """Main setup function"""
    print_header("Skin Health Detection System - Automated Setup")
    
    project_root = get_project_root()
    print_info(f"Project root: {project_root}")
    
    # Step 1: Generate SECRET_KEY
    print_header("Step 1: Generating SECRET_KEY")
    secret_key = generate_secret_key()
    print_success(f"Generated SECRET_KEY: {secret_key[:20]}...")
    
    # Step 2: Create .env file
    print_header("Step 2: Creating .env File")
    env_file = create_env_file(project_root, secret_key)
    if env_file:
        set_environment_variable("SECRET_KEY", secret_key)
    else:
        print_error("Failed to create .env file")
        return False
    
    # Step 3: Install backend dependencies
    backend_success = install_backend_dependencies(project_root)
    
    # Step 4: Install frontend dependencies
    frontend_success = install_frontend_dependencies(project_root)
    
    # Step 5: Create startup scripts
    print_header("Step 5: Creating Startup Scripts")
    create_startup_scripts(project_root, secret_key)
    
    # Step 6: Verify installation
    print_header("Step 6: Verification")
    verify_installation(project_root)
    
    # Final summary
    print_header("Setup Complete! 🎉")
    
    if platform.system() == "Windows":
        print_success("Run 'start.bat' to start the application")
        print_info("Or run these commands separately:")
        print_info("  Backend:  cd backend && uvicorn app.main:app --reload")
        print_info("  Frontend: cd frontend && npm run dev")
    else:
        print_success("Run './start.sh' to start the application")
        print_info("Or run these commands separately:")
        print_info("  Backend:  cd backend && uvicorn app.main:app --reload")
        print_info("  Frontend: cd frontend && npm run dev")
    
    print_info(f"\nConfiguration saved to: {env_file}")
    print_info("Backend will run at: http://localhost:8000")
    print_info("Frontend will run at: http://localhost:5173")
    
    return True

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print_error("\nSetup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        sys.exit(1)
